# Site settings
title: Gabriel Juchault
email: gabriel.juchault@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Gabriel Juchault's portfolio and blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://gjuchault.com" # the base hostname & protocol for your site
github_username:  gjuchault

markdown: kramdown

exclude:
  - "bower_components"
  - "bower.json"
